# Generated by Django 4.2.6 on 2023-10-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split_balance_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="Monika", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
